version: '3'

services:

    web:
        build: ./web
        environment:
            - APACHE_RUN_USER=#1000
            - PHP_IDE_CONFIG=serverName=Docker
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}

    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 2481632
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 6080:8080

    composer:
        image: composer:latest
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install

    node:
        image: node:alpine
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: sh -c "npm install && npm run watch"